import Head from 'next/head'
import RecentWorksComponents from '@/components/recentWorks/recentWorksComponent'
import Styles from  "../components/recentWorks/recentWorksComponent/recentWorksComponent.module.scss"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={Styles.projectPage}>
        <RecentWorksComponents/>
      </main>
    </>
  )
}
